# Generated by Django 5.1.3 on 2024-11-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False, verbose_name='Сыгран')),
                ('category', models.CharField(blank=True, choices=[(None, 'Вопрос default'), ('blitz', 'Блиц'), ('superblitz', 'Суперблиц'), ('blackbox', 'Чёрный ящик'), ('handout', 'Вопрос с раздаткой'), ('warm-up', 'Нулевой вопрос'), ('extra', 'Запасной вопрос'), ('bonus', 'Бонусный вопрос')], max_length=20, null=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.question', verbose_name='Текст вопроса')),
            ],
        ),
    ]
